test_set:
  architecture: one_network
  theory: LLL
  dependencies: {}
  species:
  - SiO2
  - Fe
  range:
    wavelength:
    - 100
    - 110
    particle_size:
    - 0.001
    - 0.005
  scale:
    wavelength: log
    particle_size: log
    extinction: log
    scattering: log
  quality_metric: 2
  files:
  - test_set.keras
test_set1:
  architecture: one_network
  theory: LLL
  dependencies: {}
  species:
  - SiO2
  - Fe
  range:
    wavelength:
    - 100
    - 110
    particle_size:
    - 0.001
    - 0.005
  scale:
    wavelength: log
    particle_size: log
    extinction: log
    scattering: log
  quality_metric: 2
  files:
  - test_set1.keras
