TEST_MODEL:

  architecture: 'one_network'
  dependencies: {}

  species:
    - 'SiO2'
    - 'MgSiO3'

  range: {'wavelength': [0.05, 0.1], 'particle_size': [0.001, 0.1]}

  scale: {'wavelength': 'log', 'particle_size': 'log', 'extinction': 'log', 'scattering': 'log'}

  files:
    - 'test_model.keras'

TEST_THREE:

  architecture: 'three_network'
  dependencies: {}

  species:
    - 'SiO2'
    - 'MgSiO3'

  range: {'wavelength': [0.05, 0.1], 'particle_size': [0.001, 0.1]}

  scale: {'wavelength': 'normal', 'particle_size': 'normal', 'extinction': 'normal', 'scattering': 'normal' }

  files:
    - 'test_model_0.keras'
    - 'test_model_1.keras'
    - 'test_model_2.keras'

TEST_SIX:

  architecture: 'six_network'
  dependencies: {}

  species:
    - 'SiO2'
    - 'MgSiO3'

  range: {'wavelength': [0.1, 10], 'particle_size': [0.001, 0.01]}

  scale: {'wavelength': 'normal', 'particle_size': 'normal', 'extinction': 'normal', 'scattering': 'normal' }

  files:
    - 'test_model_3.keras'
    - 'test_model_4.keras'
    - 'test_model_5.keras'
    - 'test_model_6.keras'
    - 'test_model_7.keras'
    - 'test_model_8.keras'