FORS_BROWN_DWARF:

  architecture: 'six_network'
  dependencies: {'low_wave': 1, 'high_wave': 100, 'size_cutoff': 1}

  species:
    - 'TiO2'
    - 'Fe'
    - 'Mg2SiO4'

  range: {'wavelength': [0.001, 1000], 'particle_size': [0.000159, 159]}

  scale: {'wavelength': 'log', 'particle_size': 'log', 'extinction': 'log', 'scattering': 'log'}

  files:
    - 'vmodel100rad_logmodel4_1A.keras'
    - 'vmodel100rad_logmodel4_1B.keras'
    - 'vmodel100rad_logmodel4_1C.keras'
    - 'vmodel100rad_logmodel4_2A.keras'
    - 'vmodel100rad_logmodel4_2B.keras'
    - 'vmodel100rad_logmodel4_2C.keras'

ENS_BROWN_DWARF:

  architecture: 'six_network'
  dependencies: {'low_wave': 1, 'high_wave': 100, 'size_cutoff': 1}

  species:
    - 'TiO2'
    - 'Fe'
    - 'MgSiO3'

  range: {'wavelength': [0.001, 1000], 'particle_size': [0.000159, 159]}

  scale: {'wavelength': 'log', 'particle_size': 'log', 'extinction': 'log', 'scattering': 'log'}

  files:
    - 'vmodelens_logmodel2_1A.keras'
    - 'vmodelens_logmodel2_1B.keras'
    - 'vmodelens_logmodel2_1C.keras'
    - 'vmodelens_logmodel2_2A.keras'
    - 'vmodelens_logmodel2_2B.keras'
    - 'vmodelens_logmodel2_2C.keras'

SILICATES:

  architecture: 'six_network'
  dependencies: {'low_wave': 1, 'high_wave': 100, 'size_cutoff': 1}

  species:
    - 'SiO2'
    - 'MgSiO3'
    - 'Mg2SiO4'

  range: {'wavelength': [0.001, 1000], 'particle_size': [0.000159, 159]}

  scale: {'wavelength': 'log', 'particle_size': 'log', 'extinction': 'log', 'scattering': 'log'}

  files:
    - 'vmodelsil_logmodel2_1A.keras'
    - 'vmodelsil_logmodel2_1B.keras'
    - 'vmodelsil_logmodel2_1C.keras'
    - 'vmodelsil_logmodel2_2A.keras'
    - 'vmodelsil_logmodel2_2B.keras'
    - 'vmodelsil_logmodel2_2C.keras'

METEORITE:

  architecture: 'six_network'
  dependencies: {'low_wave': 1, 'high_wave': 100, 'size_cutoff': 1}

  species:
    - 'SiO2'
    - 'MgSiO3'
    - 'Fe'

  range: {'wavelength': [0.001, 1000], 'particle_size': [0.000159, 159]}

  scale: {'wavelength': 'log', 'particle_size': 'log', 'extinction': 'log', 'scattering': 'log'}

  files:
    - 'vmodelmeteor_log_model16_1A.keras'
    - 'vmodelmeteor_log_model16_1B.keras'
    - 'vmodelmeteor_log_model16_1C.keras'
    - 'vmodelmeteor_log_model16_2A.keras'
    - 'vmodelmeteor_log_model16_2B.keras'
    - 'vmodelmeteor_log_model16_2C.keras'